### PR TITLE
Pr 192

### PR DESCRIPTION
**Pull request by cktricky**
I think this is good for release

### CODE REVIEW

**Comment by cktricky** [comment]
@mccabe615 do you want to take a look before the merge or should I just go ahead and do it?

**Comment by mccabe615** [comment]
Looks good to me. Nice work.

**Comment by cktricky** [comment]
Thanks! Also, thanks to @jasnow and @sqctest02

**Comment by jasnow** [comment]
@jasnow and @sqctest02 - Same person (smile) - You are welcome.

**Pull request merged**
