### PR TITLE
removed comments and Fixed Issue #184

### LINKED ISSUE #184: Why are solutions inlined in the code, commented out?
I think I'd prefer all of the solution code not be left in the sources remmed out, esp. since solutions are included in the tutorial. Having the commented out solutions thwarts attempts by a dev wanting to try and figure these things out (personally, I learn better if I have to solve it, rather than 'cheat'). 

I'm fine with the solution options in the tutorial, as this gives someone wanting to quickly browse example code and solutions without fixing anything.

I think removing the commented out solutions will help serve the dev who wants to dig in, while the casual dev just looking for info can go through the tutorials.

My 3 cents ;)  Thoughts?

### PR DESCRIPTION
**Pull request by cktricky**
I've removed comments to Resolve #184

### CODE REVIEW

**Comment by cktricky** [comment]
@mccabe615 you wanna take a look and merge if its 🆗 ?

**Comment by jasnow** [comment]
@cktricky - Where do you put the "back of the book" answers if you remove them from inline?

**Comment by cktricky** [comment]
The wiki contains solutions for each weakness so we'll keep them there
instead of inside the code itself. Its always been optional for users to
either leverage the written content in the wiki *OR* try to identify/fix
without the documentation (as a form of self-challenge/testing/etc.).

-- 
Ken Johnson, CTO
nVisium
775.233.8383 Mobile
*ken@nvisium.com* <ken@nvisium.com>
https://nvisium.com

Inc. 500 list of America’s fastest-growing private companies

**Comment by jasnow** [comment]
OK

**Comment by mccabe615** [comment]
I'm cool with this as long as we have enough detail in the wiki. Thanks @jasnow

**Pull request merged**
