### PR TITLE
Rails 4.0.x upgrade plus 4 gem upgrades

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded 4 gems by rebuilding Gemfile.lock file.

PLUS

** Here is the Rails 4.0.x upgrade of railsgoat.**

### CODE REVIEW

**Comment by cktricky** [comment]
@jasnow - I haven't checked the work yet but I see two separate pull requests around Rails 4.x. Do we need both or can one of them be closed?

**Comment by jasnow** [comment]
@cktricky  - I would merged them both manually at the same time.

**Comment by cktricky** [comment]
okay, I'll have to do a really good job of reviewing everything. I expect
it will take some time. Also, it won't be done until we make some
improvements and fixes in the current branch so that we can convert it to
an artifact.

On Fri, Jan 9, 2015 at 1:15 PM, Al Snow <notifications@github.com> wrote:

> @cktricky <https://github.com/cktricky> - I would merged them both
> manually at the same time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OWASP/railsgoat/pull/178#issuecomment-69374454>.
>



-- 
Ken Johnson, CTO
nVisium
(775) 233-8383

*ken.johnson@nvisium.com
<http://ken.johnson@nvisiumsecurity.com/>https://www.nvisium.com
<https://www.nvisium.com/>*

**Comment by jasnow** [comment]
I'll going to close the two pull request and then submit a brand new pull request with the changes. Think this will be simpler.

**Pull request closed without merging**
