### PR TITLE
bug(work-info): raise more useful error when key_management is missing

### LINKED ISSUE #185: undefined method `iv` for nil:NilClass
While working through fixing the goat, I fixed the work_info view to show last_four, but hadn't dug into any of the other encryption related stuff, and no users had any key_management records, which led to a confusing error `undefined method`iv' for nil:NilClass` pointing at this raise line:

```
  def iv
    raise "No IV for this User" if !(self.key_management.iv)
    self.key_management.iv
  end
```

So ... I think maybe adding another check for the presence of self.key_management along with some comments perhaps pointing the way to all of the solution code in `/tutorials/exposure`. 

(Also, this check for vi being nil in encrypt and decrypt isn't necessary since the `iv` method will raise if it is):

```
    aes.iv = iv if iv != nil
```

---

On a related note, this is an interesting example for #184 - to not include solution code in the source, just in the tutorial - in this case, adding in SSN encryption is a fair amount of work. And some of this is already in place, but not remmed out, though the seeds enhancement is remmed out ... so ... I don't have any easy answer here for the best user experience, just thinking out loud. :/

### PR DESCRIPTION
**Pull request by jmmastey**
Closes #185 

@cktricky this is one of a few places where objects related to `User` don't get initialized, and so the the app behaves poorly. What do you think about using a hook on create to make sure that these records always exist?

### CODE REVIEW

**Comment by cktricky** [comment]
@jmmastey If I understood the question correctly, the `create` action inside of the user's controller should populate the key_management info (`user_id`, and `iv`). Within the create option, we call `build_benefits_data` which is a method defined in *app/models/user.rb*

```
  def build_benefits_data
    build_retirement(POPULATE_RETIREMENTS.shuffle.first)
    build_paid_time_off(POPULATE_PAID_TIME_OFF.shuffle.first).schedule.build(POPULATE_SCHEDULE.shuffle.first)
    build_work_info(POPULATE_WORK_INFO.shuffle.first)
    # Uncomment below line to use encrypted SSN(s)
    #work_info.build_key_management(:iv => SecureRandom.hex(32))
    performance.build(POPULATE_PERFORMANCE.shuffle.first)
  end
```

You'll notice, we could populate these values by just uncommenting the following line:

`work_info.build_key_management(:iv => SecureRandom.hex(32))`

So, if you think it'll help (and if I've understood the question correctly), I'm all for uncommenting that line. Thoughts?

PR looks good 👍

**Comment by jmmastey** [comment]
I first saw this issue when creating users via the console, as opposed to the seed file or the interface. If the objects are required elsewhere in the system (they appear to be), then my suggestion would be to uncomment that line and move the build into the user model itself:

```
before_create :build_benefits_data
```

**Comment by cktricky** [comment]
Contemplated that yesterday as I was replying to you. Do you want me to merge this PR in and I'll request your review on a PR I submit for that change?

**Comment by jmmastey** [comment]
Sure, sounds good!

Joseph Mastey
@jmmastey <http://twitter.com/jmmastey>| 815.228.6924 |
http://josephmastey.com | http://chicagoapprenticeships.com

**Comment by cktricky** [comment]
👍 Thanks!

**Pull request merged**
