### PR TITLE
Upgraded 20 gems + Ruby plus pinned sqlite3 gem to avoid upgrade issue

### PR DESCRIPTION
**Pull request by jasnow**
1. Upgraded 20 gems along with Ruby to latest version (2.6.1).
2. Pinned sqlite3 gem to avoid upgrade issue.

### CODE REVIEW

**Comment by jasnow** [comment]
Travis CI build is green.

**Comment by jasnow** [comment]
Travis CI build was green.

**Comment by cktricky** [comment]
Thanks, @jasnow!

**Comment by jasnow** [comment]
U R Welcome

**Pull request merged**
