### PR TITLE
clean rubocop run

### LINKED ISSUE #264: Run Rubocop *and cry*
As @mccabe615 pointed out, we should really run a linter/rubocop against the railsgoat code-base (no, not so we can cry) - so that we can make this all look a little more professional.

### PR DESCRIPTION
**Pull request by jmmastey**
dead-or-alive-youre-cleaning-with-me

full green run. the manual changes are in a separate commit since you may want to actually read those. closes #264

### CODE REVIEW

**Comment by cktricky** [comment]
OMG 🙇  - I'll make some time to review this but thank you 🎉 🍾

**Comment by jasnow** [comment]
Can you please include fixes to the 3 remaining **rubocop** messages? Thanks.
```
Gemfile:16:5: C: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
gem 'sqlite3'
    ^^^^^^^^^
Gemfile:17:1: C: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem foreman should appear before sqlite3.
gem 'foreman'
^^^^^^^^^^^^^
Gemfile:17:5: C: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
gem 'foreman'
    ^^^^^^^^^
```

**Comment by jasnow** [comment]
I followed the **command line instructions** above to create a branch and ran my normal "rake" checks and they were all green.

**Comment by jmmastey** [comment]
Good catch, @jasnow. I think I mucked with the Gemfile somewhere and must have uncleaned my own run. I've organized the Gemfile in a more traditional way. There was no effect on Gemfile.lock when bundling.

Also, this reveals a few gems we could probably remove.

**Comment by jasnow** [comment]
which gems did you remove?

**Comment by jmmastey** [comment]
Didn't remove any, but these ones seem fairly inert:
- `aruba` I'm not aware of a cli for this app
- `minitest` unused
- `ruby-prof` unused
- `rails-pertest` unused
- `responders` should be factored out for Rails 5
- `travis-lint` deprecated

And plausibly:
- `powder` I think we removed the powify stuff from the README at least.
- `binding_of_caller`
- `launchy` appears unused

**Comment by cktricky** [comment]
Regarding the gems...

[Launchy](https://github.com/OWASP/railsgoat/pull/52) - @mccabe615 in PR 52

[Binding of caller](https://github.com/OWASP/railsgoat/pull/56) - @mccabe615 in PR 56 but specifically [for better error gem](https://github.com/OWASP/railsgoat/pull/56/commits/5177e6066995666a42be26686fdc553244b5280e)

Powder - Some people still use pow, [discussed it in Slack, here](https://owasp.slack.com/archives/C04THC44W/p1510688324000312)

**Pull request merged**
