### PR TITLE
use rubocop-github

### LINKED ISSUE #281: Update rubocop to the github rules
Currently the github ruboco gem doesn't work with the latest version of rubocop. An issue has been created. Once the issue has been resolved we should integrate the gem instead of the rules currently in use.

Issue:
https://github.com/github/rubocop-github/issues/18

### PR DESCRIPTION
**Pull request by jmmastey**
Closes #281 

If we decide to merge this, I'll make an autocorrect pass on the whole codebase. Looks like there are currently 879 offenses, 866 of which can be potentially automatically fixed.

### CODE REVIEW

**Comment by jasnow** [comment]
* Are you going to include fixes for the the other 13 (879 - 866) offenses?
 * Will this be added to (required for) the build process?

**Comment by jmmastey** [comment]
1. I can do the other 13, sure. Looks like at least one of them will probably be an exception, given it's part of a vuln.

2. I have misgivings about _requiring_ a clean run for contributing, for the sake of newer contributors. I've had good success with Hound and related libraries for at least warning folks during PRs.

**Comment by cktricky** [comment]
1. Also happy to help there but no preference on who takes it.

2. Yes, I'd also vote that we do **NOT** require passing rubocop checks in order to contribute. The whole thing was brought up so that primary contributors could start using a similar style/pattern. However, we definitely do not want to make it harder for newer folks to contribute.

**Comment by cktricky** [comment]
Everything LGTM 👍

**Pull request merged**
