### PR TITLE
Upgraded 21+ gems including Rails 4.2.7 upgrade

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded 21+ gems including Rails 4.2.7 upgrade.

### CODE REVIEW

**Comment by jasnow** [comment]
New PR

**Comment by cktricky** [comment]
@jasnow I know I'm behind on reviewing, will get to this shortly.

**Comment by cktricky** [comment]
Thanks @jasnow

**Comment by jasnow** [comment]
You are welcome as always.

**Pull request merged**
