### PR TITLE
Upgraded ~25 gems in Gemfile file

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded roughly 25 gems in Gemfile file.

### CODE REVIEW

**Comment by jasnow** [comment]
new upgrade PR - FYI

**Comment by jasnow** [comment]
Should have asked before creating PR so pruning.

**Comment by cktricky** [comment]
Al - I'm back around (travel), so did you not want to update the gems?

**Comment by jasnow** [comment]
You say assume I am always updating the gems. You just have to ask for a PR.

**Pull request closed without merging**
