### PR TITLE
Upgraded to Ruby 2.3.1 plus lots of gems

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded to Ruby 2.3.1 plus lots of gems (including: contracts, capybara, 
concurrent-ruby, foreman, listen, libv8, responders, bundler,
ruby_dep, power_asset, multi_json, brakeman).

### CODE REVIEW

**Comment by jasnow** [comment]
New PR

**Comment by jasnow** [comment]
Okay to add more gems while I wait for PR to be merged?

**Comment by jasnow** [comment]
new PR

**Comment by cktricky** [comment]
Tested and looks good, thanks @jasnow

**Pull request merged**
