### PR TITLE
Upgraded rspec 2.14.2 to 2.99.0.

### PR DESCRIPTION
**Pull request by jasnow**
* #159: Upgraded rspec 2.14.2 to 2.99.0. This is the last 2.x version of rspec before they went to 3.x.
   * This included fixing specs/tests to use new formats/conventions.
 * Upgraded misc gems by rebuilding Gemfile.lock file.

### CODE REVIEW

**Comment by jasnow** [comment]
new PR

**Comment by cktricky** [comment]
Sorry @jasnow , somehow I missed this

**Comment by cktricky** [comment]
Reviewed, bundled, tests run, etc. 👍

**Comment by jasnow** [comment]
Thanks

**Pull request merged**
