### PR TITLE
Rails 5 Candidate Branch

### PR DESCRIPTION
**Pull request by jmmastey**
Hey all,

Made a pass at upgrading Rails. Some highlights:
* Removed `mailcatcher` as a real dependency; the maintainer doesn't want to upgrade Rack and it was pegging Rails < 5. I updated the README per the gem's intended usage.
* Updated all `before_filter` to `before_action`.
* Updated the rails gem specifically, but not any of the other gems.

Some questions I could use clarification on (since this app is all about intentional breakage, it's hard to tell if some things are intentional):
  - [x] In `./app/controllers/api/v1/users_controller.rb`, the `valid_api_token` method will never cause authentication to fail. I believe there's an intentional failure in here, but specifically the last line of `identify_user` returns false, which no longer causes execution to halt.
  - [x] All `belongs_to` relationships are now required by default. I couldn't find a failure related to this change and everything looks fine, but I could use a second opinion on whether it's too much work to generate objects when these are required. I believe it's fine.
  - [x] Are there unpatched gem versions that are part of the assignment? Otherwise I'll update the other gems as well.
  - [x] There's a single test failing in maintainer mode `./spec/vulnerabilities/sql_injection_spec.rb:10` and I can't tell if it's intentional.
  - [x] Need to create a retro branch for `rails_4_2`.

### CODE REVIEW

**Comment by cktricky** [comment]
@jmmastey Apologies for the delayed response.

Responding to the checklist, in order:

1) `./app/controllers/api/v1/users_controller.rb` It is intended to halt execution if a user does not pass the token check but I'm guessing in newer versions this behaves differently based on your feedback.

2) I'm a little confused on this item (but that's probably just me).

3) While we do have some gems that are triggered by bundle-audit it is not intentional. I'm okay with keeping the gems up to date. We can tell people about A9 without actually having vulnerable gems in the project (and easier to update if required/dependent on).

4) Is the test breaking or failing?

Would it be helpful for us to setup a `rails_5` branch to submit this pull request to, instead of directly to master?

**Comment by jmmastey** [comment]
[Fixed the test](https://github.com/OWASP/railsgoat/pull/255/files#diff-4e05ad0d64e6100656b63ad1e78f32c5R29). Ironically, the way `.first` is implemented made the SQL injection no longer possible. This way should work.

Fixed the redirect. Looks like someone else was addressing gem version updates. We should be all clean now.

Two big overall questions:
* You mentioned a rails 5 branch. That'd certainly be possible. I figured that since it is the modern stable version, it'd go the other way and the _default_ version would be 5.
* Either way, the existing wiki needs to be updated to point to current versions. There are actually a few places where the existing instructions don't quite work that would also be good candidates for cleaning up, but I can't PR against the wiki.

**Comment by cktricky** [comment]
That's kind of funny re: `.first` and I think you're absolutely right that it should *end* up in master because that should be the default. I was thinking we'd place it *temporarily* in a rails_5 branch so that we can get the wiki updated plus possibly build in any new rails 5 specific issues in. Basically just staging in that branch.

How can I help with the wiki? Do you need access?

**Comment by cktricky** [comment]
Oh and I created a rails_5 branch 👍

**Comment by jmmastey** [comment]
Sounds good, targeted the new branch. Also changed a few references to R4 in the tests.


If you're game to give me access to the wiki, I can add the new pages. My plan would be to clone the existing R4 pages to have R5 versions and make whatever minor changes are necessary.

**Comment by cktricky** [comment]
Access granted (should have gotten an invite). Thanks again!

**Comment by jmmastey** [comment]
Speaking of slow response, whoops! Anyway, Rails 5 wiki page created:

https://github.com/OWASP/railsgoat/wiki/Rails-5-Tutorials

And created a few updates. None of the attacks change outright for this version, so it was mostly just verifying that each attack still worked. This should be mergeable now.

**Comment by jmmastey** [comment]
@ctricky any thoughts?

**Comment by cktricky** [comment]
I need to take some time to look at the PR but wrt wiki - l I think the
structure makes sense and if it doesn't someone is bound to let us know :-)

Thank you!

**Comment by cktricky** [comment]
@jmmastey I swear this is not being ignored, work deadlines got in the way over the 3 day weekend.

**Comment by jmmastey** [comment]
Hey @cktricky, any luck? :)

**Comment by cktricky** [comment]
Hey @jmmastey I was finally able to carve out some time and reviewed the code + changes, everything look good. 

Unit-Tests ✔️ 
DB Setup: ✔️ 
Application runs: ✔️ 
Code looked clean: ✔️ 

One item to note, I did initially receive an error of:

```
rake aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

        bin/rails db:environment:set RAILS_ENV=development

```
Which was resolved via: 

```
rails db:migrate RAILS_ENV=development
```

Next step is to sunset current branch into `4_2` and pull yours into master 👍 

Thank you!!!

**Comment by cktricky** [comment]
@jmmastey okay if I promote this into Master branch?

**Comment by jmmastey** [comment]
Awesome, glad to hear it! Thanks @cktricky

**Comment by cktricky** [comment]
So that's fine to promote to master then @jmmastey ? (just want to make sure there isn't anything you can think of that would be an issue)

**Comment by jmmastey** [comment]
Yeah, I think this is good to promote.

**Comment by cktricky** [comment]
Awesome!

**Pull request merged**
