### PR TITLE
Tuts

### PR DESCRIPTION
**Pull request by cktricky**
@mccabe615 I could use a second set of eyes on this before merging into master. Basically this removes all traces of the local tutorial (minus the ability to see the creds). Instead, we have a button in the header that gets you over to the tutorials wiki page).

### CODE REVIEW

**Comment by cktricky** [comment]
Working on trying to figure out why xss spec is failing

**Comment by jasnow** [comment]
@cktricky - I added a **sleep** to fix the xss spec in my PR - https://github.com/jasnow/railsgoat/commit/4bf596f95f959a12a81ad1525782a6165f36bea8

**Comment by cktricky** [comment]
@jasnow Thanks, I added the sleep function but the issue was the elements had changed since I modified the _header portion a bit. *Should* be good but we'll see what Travis says.

**Comment by cktricky** [comment]
Alrighty so checks are fine, I'm gonna go ahead and push this into master so I can close out issues and move on.

**Pull request merged**
