### PR TITLE
Upgraded Ruby to 2.2.3 and Rails to 4.2.4. Fixed config.serve_static_assets DEPRECATION WARNING plus upgraded gems in Gemfile

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded ruby to 2.2.3.
 * Upgraded Rails to 4.2.4.
 * Fixed config.serve_static_assets DEPRECATION WARNING. https://github.com/OWASP/railsgoat/commit/f0e1ea4027b1a9dabff81abd2ff05c70532f0f33
 * Removed libv8 temp fix in Gemfile. https://github.com/OWASP/railsgoat/commit/feb98d41b3701a52b5fede19c779e83e54f6934c
 * Upgraded 24 gems in Gemfile by rebuilding the Gemfile.lock file. (all of the other commits)

### CODE REVIEW

**Comment by jasnow** [comment]
FYI: Last two commits upgraded repo to Rails 4.2.3 and upgraded 1 gem: sprockets.

**Comment by jasnow** [comment]
Prune old pull requests.

**Comment by cktricky** [comment]
I was working on this, this morning. Should I not merge?

**Comment by jasnow** [comment]
Sure - you can merge it.

**Pull request merged**
