### PR TITLE
Upgraded Railsgoat to 4.0.13 and Ruby to 2.2.2.

### PR DESCRIPTION
**Pull request by jasnow**
1. Upgraded Railsgoat to 4.0.13.
  * Includes Fred Nixon's ( https://github.com/jfnixon  ) Strong Parameter work to remove **protected_attribute** gem.
  * Background information in previous pull requests #151 and #179.
2. Upgraded Ruby to 2.2.2.
3. Rebuild Gemfile.lock file multiple times.

### CODE REVIEW

**Comment by cktricky** [comment]
I think it might be time to visit this and stage Rails 3.x for archival, just an FYI

**Comment by jasnow** [comment]
OK - reach out if you need me.

**Comment by cktricky** [comment]
Will do, thanks again.

**Comment by cktricky** [comment]
@mccabe615 Any thoughts on how I should tag Rails 3.x work before moving onto merging this 4.x branch?

**Comment by mccabe615** [comment]
@cktricky I would suggest we keep a 3.2 branch around as some examples work better in 3.2 than 4. Plus, 3.2 is still very much a popular version out in the wild so maintaining the 3.2 branch is probably worthwhile to some folks.

**Comment by cktricky** [comment]
Understood, that makes sense.

**Comment by cktricky** [comment]
This work was pulled into branch pr-192 which, was just merged into master.

**Pull request closed without merging**
