### PR TITLE
Fix rake command in README

### PR DESCRIPTION
**Pull request by brimstone**

### CODE REVIEW

**Comment by cktricky** [comment]
Hey @jmmastey 👋 ,

Looks like this was introduced [in this commit](https://github.com/owasp/railsgoat/commit/54b8c291) and I wanted to make sure you were aware of the proposed change since you might have an opinion on it.

**Comment by brimstone** [comment]
Ah, that makes sense i suppose. I'm not a big rails guy. I was using the rails_3_2 branch and this command returned some sort of "not supported" error.

**Comment by cktricky** [comment]
Well so rather than closing this, should we consider having a 

```bash
# If using Rails 3

# If using Rails 4

# If using Rails 5
```

Or is that just overload?

**Comment by jmmastey** [comment]
Yeah, I considered for a while whether it was right to update master. Let me know if you disagree, here was my reasoning:

1. If you read the README on the rails_3_2 branch _locally_, it still reports the right command.
2. Rails 5 has been out for almost two years now, so lots of time for adoption
3. Sometime soon the rake variant of the command will just stop working, and I think it's prudent to encourage the modern usage in master.

**Comment by cktricky** [comment]
I think that updating the README.md in Master was a good move 👍  .

**Pull request closed without merging**
