### PR TITLE
Upgraded repo to Rails 4.2.7.1 and rebuilt Gemfile.lock file

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded repo to Rails 4.2.7.1 and rebuilt Gemfile.lock file (2 files changed).

### CODE REVIEW

**Comment by cktricky** [comment]
@jasnow I noticed ```Randomized with seed 9682
You're running an old version of PhantomJS, update to >= 2.1.1 for a better experience.``` when I was testing this with `RAILSGOAT_MAINTAINER='yes' rake`. Should we upgrade PhantomJS?

**Comment by jasnow** [comment]
Ran **npm install -g phantomjs-prebuilt** and now running phantomJS 2.1.1 but it does not change the Gemfile.lock file. Anything else I need to do. Thanks.

**Comment by cktricky** [comment]
I think its fine. I'm testing now and will merge if all is well. 

Thanks!

**Comment by jasnow** [comment]
Thanks you.

**Comment by cktricky** [comment]
Actually I feel bad. Should have done it sooner. Either way - merged 🎊

**Comment by mccabe615** [comment]
@jasnow can you update the readme with the pertinent info for phantomjs? If we need a certain version of phantomjs than that should be documented. Thanks for this PR!

**Comment by jasnow** [comment]
@mccabe615 - Can you please move the previous comment to separate issue? Thanks

**Pull request merged**
