### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SriHarshaGajavalli**

### CODE REVIEW

**Comment by jasnow** [comment]
Here is [some information](http://www.lessanvaezi.com/use-rails-instead-of-rake-in-rails-5)  on why we have "rails" instead of "rake" in the README file for our Rails 5 version.

**Comment by SriHarshaGajavalli** [comment]
Thanks for the information. I hope the latest update would make more sense.  If not required, we can close this PR

**Comment by cktricky** [comment]
@SriHarshaGajavalli Out of curiosity, do you know why are the errors occurring when using `rails` versus `rake`?

**Comment by jmmastey** [comment]
Maybe we could update the docs to say something like:

```
Rails 5+:
bundle exec rails db:migrate

Rails < 5:
bundle exec rake db:migrate
```

**Comment by jasnow** [comment]
@jmmastey - more than 1 place to update

**Comment by cktricky** [comment]
Hey @jmmastey in [your PR](https://github.com/OWASP/railsgoat/pull/255) you'd made this modification (switch from rake to rails) and I actually still think its a good idea to keep it as-is. Easier to maintain and if a user has an error, they can ask questions which will get us involved to help them out (get them on the right version). Also, on the older branches, we give the [correct instruction for those branches](https://github.com/OWASP/railsgoat/blob/rails_4_2/README.md).

Unless anyone strongly agrees, I think we're okay to close this one out 👍

**Pull request closed without merging**
