### PR TITLE
Invert specs (clean run)

### LINKED ISSUE #166: Specs confusing?
This one I'm not clear about but we received feedback that specs were "fixed" when they should fail and pending when they were fixed.

This could actually be the result of poor documentation on the subject because this is a new complaint we've not yet received.

### PR DESCRIPTION
**Pull request by jmmastey**
Man, that github conflict resolution really seems to have some issues for me...

Anyway, still closes #166 and replaces #268. Rubocop is pleased.

### CODE REVIEW

**Comment by cktricky** [comment]
w00t w00t. Yes last night I was taking a look but the tests were all failing so I basically focused on the review of 290, thanks for taking another crack.

**Comment by jmmastey** [comment]
Np. The rubocop change basically blew up all my outstanding PRs. Nobody to blame but myself ;)

**Comment by cktricky** [comment]
Listing out the tests that we have using `rspec -f d --color --dry-run`, and I wanted to document here for historical context if we ever go sleuthing 🔍

## 7 Tests for functionality

[Benefits Spec](https://github.com/OWASP/railsgoat/blob/master/spec/models/benefits_spec.rb)
[User Spec](https://github.com/OWASP/railsgoat/blob/master/spec/models/user_spec.rb)

## 14 Tests for vulnerabilities

[All vulnerability tests are under this folder](https://github.com/OWASP/railsgoat/tree/master/spec/vulnerabilities)

As a side note, @jmmastey before I merge this could I trouble you to make a minor change to [benefits_spec.rb](https://github.com/OWASP/railsgoat/blob/master/spec/models/benefits_spec.rb#L4) and instead of  `describe User` we `describe Benefits`? Unless you disagree, this naming convention seems like a result of copy/pasta.

**Comment by jmmastey** [comment]
@cktricky done!

**Comment by cktricky** [comment]
Awesome, thank you sir!

**Comment by jasnow** [comment]
**My Feedback**

Before this PR, when I run "rake", I get:
 * 22 examples, 15 failures

(Before) And when I run "RAILSGOAT_MAINTAINER='yes' rake", I get:
 * 22 examples, 0 failures
Note that we have no pending when RAILSGOAT_MAINTAINER variable is set.

After this PR, when I run "rake", I get:
 * 21 examples, 14 failures

(After) And when I run "RAILSGOAT_MAINTAINER='yes' rake", I get:
 * 21 examples, 0 failures, 14 pending

(After) Therefore we have lost 1 example and gained 14 pending and
LOTS of OUTPUT even with RAILSGOAT_MAINTAINER variable set.

NOTE: This is the command I used to go back before the PR:
 * "git reset --hard b4eb845f4fdeb45af73ab92dabf9d54c07f18090"

**Comment by jmmastey** [comment]
Sorry this has caused so much consternation!

The change "pending unless you're a maintainer", to "failing unless you're a maintainer" was the intention behind the change, per #166. The one test that went away, I'll take a look; it's been a few months now.

I do like the idea of reducing test suite output overall. That said, running as a maintainer will only show pending output if there are no "true" failures. Otherwise, you'll just get the red output.

**Comment by jasnow** [comment]
Note that my commit (b4eb845f4fdeb45af73ab92dabf9d54c07f18090) mentioned above was dated 12/15/2017.

**Pull request merged**
