### PR TITLE
Fixed #225 (rspec upgrade from 2.99.0 to latest 3.x)

### LINKED ISSUE #225: Convert rspec 2.99 to 3.0.x including the changed "pending" role in Railsgoat project.
Convert rspec 2.99 to 3.0.x including the changed "pending" role in Railsgoat project.

Separated #159 into 2 issues.

### PR DESCRIPTION
**Pull request by jasnow**
* Fixed #225 (rspec upgrade from 2.99.0 to latest 3.x)
   * Main issue here is how to upgrade **conditional pending** since it went away for rspec 3.x.
 * Upgraded capybara gem.

### CODE REVIEW

**Comment by jasnow** [comment]
new PR

**Comment by jasnow** [comment]
Anything else I need to do to prepare for the merge?

**Comment by cktricky** [comment]
@mccabe615 Can you tell me whether or not you are also having issues getting therubyracer installed on OSX?

**Comment by cktricky** [comment]
@jasnow I'm not sure. Been fighting with `therubyracer` to get it installed on OSX.

**Comment by jasnow** [comment]
@cktricky - What's the message from therubyracer?

**Comment by cktricky** [comment]
```compiling accessor.cc
clang: warning: argument unused during compilation: '-rdynamic'
In file included from accessor.cc:1:
In file included from ./rr.h:4:
/usr/local/opt/v8/include/v8.h:343:16: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using Handle = Local<T>;
               ^
/usr/local/opt/v8/include/v8.h:360:33: error: use of undeclared identifier 'nullptr'
  V8_INLINE MaybeLocal() : val_(nullptr) {}
                                ^
/usr/local/opt/v8/include/v8.h:367:51: error: use of undeclared identifier 'nullptr'
  V8_INLINE bool IsEmpty() const { return val_ == nullptr; }
                                                  ^
/usr/local/opt/v8/include/v8.h:371:29: error: use of undeclared identifier 'nullptr'
    out->val_ = IsEmpty() ? nullptr : this->val_;
                            ^
/usr/local/opt/v8/include/v8.h:437:50: error: use of undeclared identifier 'nullptr'
  bool IsFirstPass() const { return callback_ != nullptr; }
                                                 ^
/usr/local/opt/v8/include/v8.h:476:29: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using PhantomCallbackData = WeakCallbackInfo<T>;
                            ^
/usr/local/opt/v8/include/v8.h:479:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class WeakCallbackType { kParameter, kInternalFields };
     ^
/usr/local/opt/v8/include/v8.h:655:49: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  PersistentBase(const PersistentBase& other) = delete;  // NOLINT
                                                ^
/usr/local/opt/v8/include/v8.h:656:43: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  void operator=(const PersistentBase&) = delete;
                                          ^
/usr/local/opt/v8/include/v8.h:832:26: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
  V8_INLINE Global(Global&& other) : PersistentBase<T>(other.val_) {  // NOLINT
                         ^
/usr/local/opt/v8/include/v8.h:840:40: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
  V8_INLINE Global& operator=(Global<S>&& rhs) {  // NOLINT
                                       ^
/usr/local/opt/v8/include/v8.h:862:27: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  Global(const Global&) = delete;
                          ^
/usr/local/opt/v8/include/v8.h:863:35: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  void operator=(const Global&) = delete;
                                  ^
/usr/local/opt/v8/include/v8.h:808:42: error: use of undeclared identifier 'nullptr'
  V8_INLINE Global() : PersistentBase<T>(nullptr) {}
                                         ^
/usr/local/opt/v8/include/v8.h:833:18: error: use of undeclared identifier 'nullptr'
    other.val_ = nullptr;
                 ^
/usr/local/opt/v8/include/v8.h:845:18: error: use of undeclared identifier 'nullptr'
      rhs.val_ = nullptr;
                 ^
/usr/local/opt/v8/include/v8.h:852:44: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
  Global Pass() { return static_cast<Global&&>(*this); }  // NOLINT
                                           ^
/usr/local/opt/v8/include/v8.h:870:26: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
using UniquePersistent = Global<T>;
                         ^
/usr/local/opt/v8/include/v8.h:1110:52: error: use of undeclared identifier 'nullptr'
                            ScriptOrigin* origin = nullptr));
                                                   ^
/usr/local/opt/v8/include/v8.h:1113:30: error: use of undeclared identifier 'nullptr'
      ScriptOrigin* origin = nullptr);
                             ^
/usr/local/opt/v8/include/v8.h:2092:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class NewStringType { kNormal, kInternalized };
     ^
/usr/local/opt/v8/include/v8.h:2302:42: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
    kNormalString = static_cast<int>(v8::NewStringType::kNormal),
                                         ^
/usr/local/opt/v8/include/v8.h:2303:48: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
    kInternalizedString = static_cast<int>(v8::NewStringType::kInternalized)
                                               ^
/usr/local/opt/v8/include/v8.h:3242:36: error: use of undeclared identifier 'nullptr'
    return NewInstance(context, 0, nullptr);
                                   ^
/usr/local/opt/v8/include/v8.h:3420:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class ArrayBufferCreationMode { kInternalized, kExternalized };
     ^
/usr/local/opt/v8/include/v8.h:3504:38: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
      ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                     ^
/usr/local/opt/v8/include/v8.h:3867:38: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
      ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                     ^
/usr/local/opt/v8/include/v8.h:4457:57: error: use of undeclared identifier 'nullptr'
      experimental::FastAccessorBuilder* fast_handler = nullptr,
                                                        ^
/usr/local/opt/v8/include/v8.h:4473:57: error: use of undeclared identifier 'nullptr'
      experimental::FastAccessorBuilder* fast_handler = nullptr);
                                                        ^
/usr/local/opt/v8/include/v8.h:4543:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class PropertyHandlerFlags {
     ^
/usr/local/opt/v8/include/v8.h:4565:36: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
      PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                                   ^
/usr/local/opt/v8/include/v8.h:4593:36: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
      PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                                   ^
/usr/local/opt/v8/include/v8.h:7292:27: error: use of undeclared identifier 'nullptr'
  if (V8_UNLIKELY(val_ == nullptr)) V8::ToLocalEmpty();
                          ^
/usr/local/opt/v8/include/v8.h:7746:46: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
  Set(v8::String::NewFromUtf8(isolate, name, NewStringType::kNormal)
                                             ^
In file included from accessor.cc:1:
./rr.h:358:39: error: no member named 'ScriptData' in namespace 'v8'
class ScriptData : public Pointer<v8::ScriptData> {
                                  ~~~~^
./rr.h:358:51: error: expected class name
class ScriptData : public Pointer<v8::ScriptData> {
                                                  ^
./rr.h:360:21: error: no type named 'ScriptData' in namespace 'v8'; did you mean simply 'ScriptData'?
  inline ScriptData(v8::ScriptData* d) : Pointer<v8::ScriptData>(d) {};
                    ^~~~~~~~~~~~~~
                    ScriptData
./rr.h:358:7: note: 'ScriptData' declared here
class ScriptData : public Pointer<v8::ScriptData> {
      ^
./rr.h:360:54: error: no member named 'ScriptData' in namespace 'v8'
  inline ScriptData(v8::ScriptData* d) : Pointer<v8::ScriptData>(d) {};
                                                 ~~~~^
./rr.h:360:65: error: expected class member or base class name
  inline ScriptData(v8::ScriptData* d) : Pointer<v8::ScriptData>(d) {};
                                                                ^
./rr.h:360:65: error: expected '{' or ','
fatal error: too many errors emitted, stopping now [-ferror-limit=]
21 warnings and 20 errors generated.
make: *** [accessor.o] Error 1

make failed, exit code 2```

**Comment by cktricky** [comment]
compiling accessor.cc
    clang: warning: argument unused during compilation: '-rdynamic'
    In file included from accessor.cc:1:
    In file included from ./rr.h:4:
    /usr/local/opt/v8/include/v8.h:343:16: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
    using Handle = Local<T>;
                   ^
    /usr/local/opt/v8/include/v8.h:360:33: error: use of undeclared identifier 'nullptr'
      V8_INLINE MaybeLocal() : val_(nullptr) {}
                                    ^
    /usr/local/opt/v8/include/v8.h:367:51: error: use of undeclared identifier 'nullptr'
      V8_INLINE bool IsEmpty() const { return val_ == nullptr; }
                                                      ^
    /usr/local/opt/v8/include/v8.h:371:29: error: use of undeclared identifier 'nullptr'
        out->val_ = IsEmpty() ? nullptr : this->val_;
                                ^
    /usr/local/opt/v8/include/v8.h:437:50: error: use of undeclared identifier 'nullptr'
      bool IsFirstPass() const { return callback_ != nullptr; }
                                                     ^
    /usr/local/opt/v8/include/v8.h:476:29: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
    using PhantomCallbackData = WeakCallbackInfo<T>;
                                ^
    /usr/local/opt/v8/include/v8.h:479:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
    enum class WeakCallbackType { kParameter, kInternalFields };
         ^
    /usr/local/opt/v8/include/v8.h:655:49: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
      PersistentBase(const PersistentBase& other) = delete;  // NOLINT
                                                    ^
    /usr/local/opt/v8/include/v8.h:656:43: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
      void operator=(const PersistentBase&) = delete;
                                              ^
    /usr/local/opt/v8/include/v8.h:832:26: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      V8_INLINE Global(Global&& other) : PersistentBase<T>(other.val_) {  // NOLINT
                             ^
    /usr/local/opt/v8/include/v8.h:840:40: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      V8_INLINE Global& operator=(Global<S>&& rhs) {  // NOLINT
                                           ^
    /usr/local/opt/v8/include/v8.h:862:27: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
      Global(const Global&) = delete;
                              ^
    /usr/local/opt/v8/include/v8.h:863:35: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
      void operator=(const Global&) = delete;
                                      ^
    /usr/local/opt/v8/include/v8.h:808:42: error: use of undeclared identifier 'nullptr'
      V8_INLINE Global() : PersistentBase<T>(nullptr) {}
                                             ^
    /usr/local/opt/v8/include/v8.h:833:18: error: use of undeclared identifier 'nullptr'
        other.val_ = nullptr;
                     ^
    /usr/local/opt/v8/include/v8.h:845:18: error: use of undeclared identifier 'nullptr'
          rhs.val_ = nullptr;
                     ^
    /usr/local/opt/v8/include/v8.h:852:44: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      Global Pass() { return static_cast<Global&&>(*this); }  // NOLINT
                                               ^
    /usr/local/opt/v8/include/v8.h:870:26: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
    using UniquePersistent = Global<T>;
                             ^
    /usr/local/opt/v8/include/v8.h:1110:52: error: use of undeclared identifier 'nullptr'
                                ScriptOrigin* origin = nullptr));
                                                       ^
    /usr/local/opt/v8/include/v8.h:1113:30: error: use of undeclared identifier 'nullptr'
          ScriptOrigin* origin = nullptr);
                                 ^
    /usr/local/opt/v8/include/v8.h:2092:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
    enum class NewStringType { kNormal, kInternalized };
         ^
    /usr/local/opt/v8/include/v8.h:2302:42: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
        kNormalString = static_cast<int>(v8::NewStringType::kNormal),
                                             ^
    /usr/local/opt/v8/include/v8.h:2303:48: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
        kInternalizedString = static_cast<int>(v8::NewStringType::kInternalized)
                                                   ^
    /usr/local/opt/v8/include/v8.h:3242:36: error: use of undeclared identifier 'nullptr'
        return NewInstance(context, 0, nullptr);
                                       ^
    /usr/local/opt/v8/include/v8.h:3420:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
    enum class ArrayBufferCreationMode { kInternalized, kExternalized };
         ^
    /usr/local/opt/v8/include/v8.h:3504:38: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
          ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                         ^
    /usr/local/opt/v8/include/v8.h:3867:38: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
          ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                         ^
    /usr/local/opt/v8/include/v8.h:4457:57: error: use of undeclared identifier 'nullptr'
          experimental::FastAccessorBuilder* fast_handler = nullptr,
                                                            ^
    /usr/local/opt/v8/include/v8.h:4473:57: error: use of undeclared identifier 'nullptr'
          experimental::FastAccessorBuilder* fast_handler = nullptr);
                                                            ^
    /usr/local/opt/v8/include/v8.h:4543:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
    enum class PropertyHandlerFlags {
         ^
    /usr/local/opt/v8/include/v8.h:4565:36: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
          PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                                       ^
    /usr/local/opt/v8/include/v8.h:4593:36: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
          PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
                                       ^
    /usr/local/opt/v8/include/v8.h:7292:27: error: use of undeclared identifier 'nullptr'
      if (V8_UNLIKELY(val_ == nullptr)) V8::ToLocalEmpty();
                              ^
    /usr/local/opt/v8/include/v8.h:7746:46: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
      Set(v8::String::NewFromUtf8(isolate, name, NewStringType::kNormal)
                                                 ^
    In file included from accessor.cc:1:
    ./rr.h:358:39: error: no member named 'ScriptData' in namespace 'v8'
    class ScriptData : public Pointer<v8::ScriptData> {
                                      ~~~~^
    ./rr.h:358:51: error: expected class name
    class ScriptData : public Pointer<v8::ScriptData> {
                                                      ^
    ./rr.h:360:21: error: no type named 'ScriptData' in namespace 'v8'; did you mean simply 'ScriptData'?
      inline ScriptData(v8::ScriptData* d) : Pointer<v8::ScriptData>(d) {};
                        ^~~~~~~~~~~~~~
                        ScriptData
    ./rr.h:358:7: note: 'ScriptData' declared here
    class ScriptData : public Pointer<v8::ScriptData> {
          ^
    ./rr.h:360:54: error: no member named 'ScriptData' in namespace 'v8'
      inline ScriptData(v8::ScriptData* d) : Pointer<v8::ScriptData>(d) {};
                                                     ~~~~^
    ./rr.h:360:65: error: expected class member or base class name
      inline ScriptData(v8::ScriptData* d) : Pointer<v8::ScriptData>(d) {};
                                                                    ^
    ./rr.h:360:65: error: expected '{' or ','
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    21 warnings and 20 errors generated.
    make: *** [accessor.o] Error 1
    
    make failed, exit code 2

**Comment by cktricky** [comment]
I seem to only have the issue with Ruby 2.3.0

**Comment by mccabe615** [comment]
I haven't had an issue getting it installed. I'm on Ruby 2.3.0 and OSX 10.10.5 Yosemite

**Comment by jasnow** [comment]
Guess: Try this: http://stackoverflow.com/questions/24081473/how-to-install-therubyracer-gem-on-10-10-yosemite

I am on Ruby 2.4.0 and El Capitan.

**Comment by jasnow** [comment]
Hit your problem this afternoon and fixed it with:
```
brew tap homebrew/versions
brew install v8-315
brew link --force v8-315
gem install libv8 -- --with-system-v8
gem install therubyracer
bundle (green)
```

**Comment by cktricky** [comment]
Thanks @jasnow. I know I'd tried this before and didn't work but here is why I think it did this time (and seriously, thanks again!)

Last time when I ran into a brew error about already having v8 linked, I think I did something like:

`brew link --overwrite v8-315` and it definitely did not pan out well.

However, doing:

`brew unlink v8` *first* and then `brew link --force v8-315` worked. Cheers man and later tonight or early tomorrow morning I'll make sure we get this merged.

**Comment by jasnow** [comment]
v8 is always a pain.

**Comment by cktricky** [comment]
All good. Tested & Reviewed. Cheers :metal:

**Comment by jasnow** [comment]
Thanks

**Pull request merged**
